all:
	g++ -o SenderSR SenderSR.cpp -lpthread
	g++ -o ReceiverSR ReceiverSR.cpp -lpthread
	g++ -o SenderGBN SenderGBN.cpp -lpthread
	g++ -o ReceiverGBN ReceiverGBN.cpp -lpthread

clean:
	rm SenderSR ReceiverSR SenderGBN ReceiverGBN
